//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/Editor/Cheats/EditorControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Netologia.Necro.Editor.Cheates
{
    public partial class @EditorControls : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @EditorControls()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""EditorControls"",
    ""maps"": [
        {
            ""name"": ""Cheats"",
            ""id"": ""e3466d08-7cd6-4224-8c55-257c6fbfb856"",
            ""actions"": [
                {
                    ""name"": ""NextTurn"",
                    ""type"": ""Button"",
                    ""id"": ""c6786a29-455a-4a3a-af4a-59b7a696bd07"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Kill"",
                    ""type"": ""Button"",
                    ""id"": ""a5dd92e2-43a3-4232-9770-dfe1a6c857fc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""24fd2d06-cd1e-45ff-9bd3-7ba9ce4a2e2a"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextTurn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dc465f98-b751-4afb-8d9e-09f069aee756"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Kill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Cheats
            m_Cheats = asset.FindActionMap("Cheats", throwIfNotFound: true);
            m_Cheats_NextTurn = m_Cheats.FindAction("NextTurn", throwIfNotFound: true);
            m_Cheats_Kill = m_Cheats.FindAction("Kill", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Cheats
        private readonly InputActionMap m_Cheats;
        private ICheatsActions m_CheatsActionsCallbackInterface;
        private readonly InputAction m_Cheats_NextTurn;
        private readonly InputAction m_Cheats_Kill;
        public struct CheatsActions
        {
            private @EditorControls m_Wrapper;
            public CheatsActions(@EditorControls wrapper) { m_Wrapper = wrapper; }
            public InputAction @NextTurn => m_Wrapper.m_Cheats_NextTurn;
            public InputAction @Kill => m_Wrapper.m_Cheats_Kill;
            public InputActionMap Get() { return m_Wrapper.m_Cheats; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(CheatsActions set) { return set.Get(); }
            public void SetCallbacks(ICheatsActions instance)
            {
                if (m_Wrapper.m_CheatsActionsCallbackInterface != null)
                {
                    @NextTurn.started -= m_Wrapper.m_CheatsActionsCallbackInterface.OnNextTurn;
                    @NextTurn.performed -= m_Wrapper.m_CheatsActionsCallbackInterface.OnNextTurn;
                    @NextTurn.canceled -= m_Wrapper.m_CheatsActionsCallbackInterface.OnNextTurn;
                    @Kill.started -= m_Wrapper.m_CheatsActionsCallbackInterface.OnKill;
                    @Kill.performed -= m_Wrapper.m_CheatsActionsCallbackInterface.OnKill;
                    @Kill.canceled -= m_Wrapper.m_CheatsActionsCallbackInterface.OnKill;
                }
                m_Wrapper.m_CheatsActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @NextTurn.started += instance.OnNextTurn;
                    @NextTurn.performed += instance.OnNextTurn;
                    @NextTurn.canceled += instance.OnNextTurn;
                    @Kill.started += instance.OnKill;
                    @Kill.performed += instance.OnKill;
                    @Kill.canceled += instance.OnKill;
                }
            }
        }
        public CheatsActions @Cheats => new CheatsActions(this);
        public interface ICheatsActions
        {
            void OnNextTurn(InputAction.CallbackContext context);
            void OnKill(InputAction.CallbackContext context);
        }
    }
}
